name: Demo CI workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run Command 1
        run: echo "Command 1"

      - name: Run Command 2
        run: echo "Command 2"
